
#ifndef CHESS_ENGINE_MACROS_H
#define CHESS_ENGINE_MACROS_H

#define NUMBER_IN_BOUNDS(NUMBER, MINIMUM, MAXIMUM) (NUMBER >= MINIMUM && NUMBER <= MAXIMUM)

#define ABS_SHORT_NUMBER(NUMBER) (((NUMBER) >> 15) ^ (NUMBER)) - ((NUMBER) >> 15)

#endif
