
#ifndef ENGINE_FIELD_KINGS_H
#define ENGINE_FIELD_KINGS_H

typedef unsigned short Kings;

#define KINGS_WHITE_MACRO(KINGS) ( (KINGS & KINGS_WHITE_MASK) >> KINGS_WHITE_SHIFT)
#define KINGS_BLACK_MACRO(KINGS) ( (KINGS & KINGS_BLACK_MASK) >> KINGS_BLACK_SHIFT)

#define WHITE_KINGS_MACRO(WHITE) ( (WHITE << KINGS_WHITE_SHIFT) & KINGS_WHITE_MASK)
#define BLACK_KINGS_MACRO(BLACK) ( (BLACK << KINGS_BLACK_SHIFT) & KINGS_BLACK_MASK)

#define ALLOC_KINGS_WHITE(KINGS, WHITE) ( (KINGS & ~KINGS_WHITE_MASK) | (WHITE & KINGS_WHITE_MASK) )
#define ALLOC_KINGS_BLACK(KINGS, BLACK) ( (KINGS & ~KINGS_BLACK_MASK) | (BLACK & KINGS_BLACK_MASK) )

extern const Kings KINGS_WHITE_MASK;
extern const Kings KINGS_BLACK_MASK;

extern const unsigned short KINGS_WHITE_SHIFT;
extern const unsigned short KINGS_BLACK_SHIFT;

extern const Kings KINGS_NONE;
extern const Kings KINGS_BLANK;

#endif
