
#ifndef ENGINE_STRUCT_MACROS_H
#define ENGINE_STRUCT_MACROS_H

#define MOVE_STOP_MACRO(MOVE) ( (MOVE & MOVE_STOP_MASK) >> MOVE_STOP_SHIFT)
#define MOVE_START_MACRO(MOVE) ( (MOVE & MOVE_START_MASK) >> MOVE_START_SHIFT)

#define INFO_TEAM_MACRO(INFO) ( (INFO & INFO_TEAM_MASK) >> INFO_TEAM_SHIFT)
#define INFO_PASSANT_MACRO(INFO) ( (INFO & INFO_PASSANT_MASK) >> INFO_PASSANT_SHIFT)
#define INFO_TURNS_MACRO(INFO) ( (INFO & INFO_TURNS_MASK) >> INFO_TURNS_SHIFT)
#define INFO_COUNTER_MACRO(INFO) ( (INFO & INFO_COUNTER_MASK) >> INFO_COUNTER_SHIFT)

#define POINT_RANK_MACRO(POINT) ( (POINT & POINT_RANK_MASK) >> POINT_RANK_SHIFT)
#define POINT_FILE_MACRO(POINT) ( (POINT & POINT_FILE_MASK) >> POINT_FILE_SHIFT)

#define PIECE_TEAM_MACRO(PIECE) ( (PIECE & PIECE_TEAM_MASK) >> PIECE_TEAM_SHIFT)
#define PIECE_TYPE_MACRO(PIECE) ( (PIECE & PIECE_TYPE_MASK) >> PIECE_TYPE_SHIFT)

#define KINGS_WHITE_MACRO(KINGS) ( (KINGS & KINGS_WHITE_MASK) >> KINGS_WHITE_SHIFT)
#define KINGS_BLACK_MACRO(KINGS) ( (KINGS & KINGS_BLACK_MASK) >> KINGS_BLACK_SHIFT)


#define STOP_MOVE_MACRO(STOP) ( (STOP << MOVE_STOP_SHIFT) & MOVE_STOP_MASK)
#define START_MOVE_MACRO(START) ( (START << MOVE_START_SHIFT) & MOVE_START_MASK)

#define TEAM_INFO_MACRO(TEAM) ( (TEAM << INFO_TEAM_SHIFT) & INFO_TEAM_MASK)
#define PASSANT_INFO_MACRO(PASSANT) ( (PASSANT << INFO_PASSANT_SHIFT) & INFO_PASSANT_MASK)
#define TURNS_INFO_MACRO(TURNS) ( (TURNS << INFO_TURNS_SHIFT) & INFO_TURNS_MASK)
#define COUNTER_INFO_MACRO(COUNTER) ( (COUNTER << INFO_COUNTER_SHIFT) & INFO_COUNTER_MASK)

#define RANK_POINT_MACRO(RANK) ( (RANK << POINT_RANK_SHIFT) & POINT_RANK_MASK)
#define FILE_POINT_MACRO(FILE) ( (FILE << POINT_FILE_SHIFT) & POINT_FILE_MASK)

#define TEAM_PIECE_MACRO(TEAM) ( (TEAM << PIECE_TEAM_SHIFT) & PIECE_TEAM_MASK)
#define TYPE_PIECE_MACRO(TYPE) ( (TYPE << PIECE_TYPE_SHIFT) & PIECE_TYPE_MASK)

#define WHITE_KINGS_MACRO(WHITE) ( (WHITE << KINGS_WHITE_SHIFT) & KINGS_WHITE_MASK)
#define BLACK_KINGS_MACRO(BLACK) ( (BLACK << KINGS_BLACK_SHIFT) & KINGS_BLACK_MASK)


#define ALLOC_MOVE_FLAG(MOVE, FLAG) ( (MOVE & ~MOVE_FLAG_MASK) | (FLAG & MOVE_FLAG_MASK) )
#define ALLOC_MOVE_STOP(MOVE, STOP) ( (MOVE & ~MOVE_STOP_MASK) | (STOP & MOVE_STOP_MASK) )
#define ALLOC_MOVE_START(MOVE, START) ( (MOVE & ~MOVE_START_MASK) | (START & MOVE_START_MASK) )

#define ALLOC_INFO_TEAM(INFO, TEAM) ( (INFO & ~INFO_TEAM_MASK) | (TEAM & INFO_TEAM_MASK) )
#define ALLOC_INFO_PASSANT(INFO, PASSANT) ( (INFO & ~INFO_PASSANT_MASK) | (PASSANT & INFO_PASSANT_MASK) )
#define ALLOC_INFO_TURNS(INFO, TURNS) ( (INFO & ~INFO_TURNS_MASK) | (TURNS & INFO_TURNS_MASK) )
#define ALLOC_INFO_COUNTER(INFO, COUNTER) ( (INFO & ~INFO_COUNTER_MASK) | (COUNTER & INFO_COUNTER_MASK) )
#define ALLOC_INFO_CASTLES(INFO, CASTLES) ( (INFO & ~INFO_CASTLES_MASK) | (CASTLES & INFO_CASTLES_MASK) )

#define ALLOC_POINT_RANK(POINT, RANK) ( (POINT & ~POINT_RANK_MASK) | (RANK & POINT_RANK_MASK) )
#define ALLOC_POINT_FILE(POINT, FILE) ( (POINT & ~POINT_FILE_MASK) | (FILE & POINT_FILE_MASK) )

#define ALLOC_PIECE_TEAM(PIECE, TEAM) ( (PIECE & ~PIECE_TEAM_MASK) | (TEAM & PIECE_TEAM_MASK) )
#define ALLOC_PIECE_TYPE(PIECE, TYPE) ( (PIECE & ~PIECE_TYPE_MASK) | (TYPE & PIECE_TYPE_MASK) )

#define ALLOC_KINGS_WHITE(KINGS, WHITE) ( (KINGS & ~KINGS_WHITE_MASK) | (WHITE & KINGS_WHITE_MASK) )
#define ALLOC_KINGS_BLACK(KINGS, BLACK) ( (KINGS & ~KINGS_BLACK_MASK) | (BLACK & KINGS_BLACK_MASK) )

#endif
