
#ifndef ENGINE_FIELD_INFO_H
#define ENGINE_FIELD_INFO_H

typedef unsigned int Info;

#define INFO_TEAM_MACRO(INFO) ((INFO & INFO_TEAM_MASK) >> INFO_TEAM_SHIFT)
#define INFO_PASSANT_MACRO(INFO) ((INFO & INFO_PASSANT_MASK) >> INFO_PASSANT_SHIFT)
#define INFO_TURNS_MACRO(INFO) ((INFO & INFO_TURNS_MASK) >> INFO_TURNS_SHIFT)
#define INFO_COUNTER_MACRO(INFO) ((INFO & INFO_COUNTER_MASK) >> INFO_COUNTER_SHIFT)

#define TEAM_INFO_MACRO(TEAM) ((TEAM << INFO_TEAM_SHIFT) & INFO_TEAM_MASK)
#define PASSANT_INFO_MACRO(PASSANT) ((PASSANT << INFO_PASSANT_SHIFT) & INFO_PASSANT_MASK)
#define TURNS_INFO_MACRO(TURNS) ((TURNS << INFO_TURNS_SHIFT) & INFO_TURNS_MASK)
#define COUNTER_INFO_MACRO(COUNTER) ((COUNTER << INFO_COUNTER_SHIFT) & INFO_COUNTER_MASK)

#define ALLOC_INFO_TEAM(INFO, TEAM) ((INFO & ~INFO_TEAM_MASK) | (TEAM & INFO_TEAM_MASK))
#define ALLOC_INFO_PASSANT(INFO, PASSANT) ((INFO & ~INFO_PASSANT_MASK) | (PASSANT & INFO_PASSANT_MASK))
#define ALLOC_INFO_TURNS(INFO, TURNS) ((INFO & ~INFO_TURNS_MASK) | (TURNS & INFO_TURNS_MASK))
#define ALLOC_INFO_COUNTER(INFO, COUNTER) ((INFO & ~INFO_COUNTER_MASK) | (COUNTER & INFO_COUNTER_MASK))
#define ALLOC_INFO_CASTLES(INFO, CASTLES) ((INFO & ~INFO_CASTLES_MASK) | (CASTLES & INFO_CASTLES_MASK))

#define CLEAR_WHITE_CASTLE(INFO) (INFO & ~INFO_WHITE_KSIDE & ~INFO_WHITE_QSIDE)
#define CLEAR_BLACK_CASTLE(INFO) (INFO & ~INFO_BLACK_KSIDE & ~INFO_BLACK_QSIDE)

#define CLEAR_WHITE_KSIDE(INFO) (INFO & ~INFO_WHITE_KSIDE)
#define CLEAR_WHITE_QSIDE(INFO) (INFO & ~INFO_WHITE_QSIDE)
#define CLEAR_BLACK_KSIDE(INFO) (INFO & ~INFO_BLACK_KSIDE)
#define CLEAR_BLACK_QSIDE(INFO) (INFO & ~INFO_BLACK_QSIDE)

#define CLEAR_INFO_PASSANT(INFO) (INFO & ~INFO_PASSANT_MASK)

#define MASK_INFO_TEAM(INFO) (INFO & INFO_TEAM_MASK)

#define MASK_WHITE_KSIDE(INFO) (INFO & INFO_WHITE_KSIDE)
#define MASK_WHITE_QSIDE(INFO) (INFO & INFO_WHITE_QSIDE)
#define MASK_BLACK_KSIDE(INFO) (INFO & INFO_BLACK_KSIDE)
#define MASK_BLACK_QSIDE(INFO) (INFO & INFO_BLACK_QSIDE)

extern const Info INFO_TEAM_MASK;
extern const Info INFO_PASSANT_MASK;
extern const Info INFO_CASTLES_MASK;
extern const Info INFO_TURNS_MASK;
extern const Info INFO_COUNTER_MASK;

extern const Info INFO_WHITE_KSIDE;
extern const Info INFO_WHITE_QSIDE;
extern const Info INFO_BLACK_KSIDE;
extern const Info INFO_BLACK_QSIDE;

extern const Info INFO_TEAM_NONE;
extern const Info INFO_TEAM_WHITE;
extern const Info INFO_TEAM_BLACK;

extern const unsigned short INFO_TEAM_SHIFT;
extern const unsigned short INFO_PASSANT_SHIFT;
extern const unsigned short INFO_TURNS_SHIFT;
extern const unsigned short INFO_COUNTER_SHIFT;

extern const Info INFO_NONE;
extern const Info INFO_BLANK;

#endif
