
#ifndef ENGINE_FIELD_POINT_H
#define ENGINE_FIELD_POINT_H

typedef signed short Point;

#define POINT_RANK_MACRO(POINT) ((POINT & POINT_RANK_MASK) >> POINT_RANK_SHIFT)
#define POINT_FILE_MACRO(POINT) ((POINT & POINT_FILE_MASK) >> POINT_FILE_SHIFT)

#define RANK_POINT_MACRO(RANK) ((RANK << POINT_RANK_SHIFT) & POINT_RANK_MASK)
#define FILE_POINT_MACRO(FILE) ((FILE << POINT_FILE_SHIFT) & POINT_FILE_MASK)

#define ALLOC_POINT_RANK(POINT, RANK) ((POINT & ~POINT_RANK_MASK) | (RANK & POINT_RANK_MASK))
#define ALLOC_POINT_FILE(POINT, FILE) ((POINT & ~POINT_FILE_MASK) | (FILE & POINT_FILE_MASK))

#define POINT_INSIDE_BOARD(POINT) NUMBER_IN_BOUNDS(POINT, 0, BOARD_LENGTH - 1)
#define POINTS_INSIDE_BOARD(POINT1, POINT2) (POINT_INSIDE_BOARD(POINT1) && POINT_INSIDE_BOARD(POINT2))

#define RANK_INSIDE_BOARD(RANK) NUMBER_IN_BOUNDS(RANK, 0, BOARD_RANKS - 1)
#define FILE_INSIDE_BOARD(FILE) NUMBER_IN_BOUNDS(FILE, 0, BOARD_FILES - 1)

#define RANK_FILE_INSIDE(RANK, FILE) (RANK_INSIDE_BOARD(RANK) && FILE_INSIDE_BOARD(FILE))

#define RANK_FILE_POINT(RANK, FILE) (RANK_POINT_MACRO(RANK) | FILE_POINT_MACRO(FILE))

extern const Point POINT_RANK_MASK;
extern const Point POINT_FILE_MASK;

extern const unsigned short POINT_RANK_SHIFT;
extern const unsigned short POINT_FILE_SHIFT;

extern const Point POINT_NONE;
extern const Point POINT_BLANK;

#endif
