
#ifndef CHESS_ENGINE_MACROS_H
#define CHESS_ENGINE_MACROS_H

#define NUMBER_IN_BOUNDS(NUMBER, MINIMUM, MAXIMUM) (NUMBER >= MINIMUM && NUMBER <= MAXIMUM)

#define MAX_NUMBER_VALUE(NUMBER1, NUMBER2) ((NUMBER2 > NUMBER1) ? NUMBER2 : NUMBER1)

#define MIN_NUMBER_VALUE(NUMBER1, NUMBER2) ((NUMBER2 < NUMBER1) ? NUMBER2 : NUMBER1)

#define TEAM_WEIGHT_SCORE(SCORE, TEAM) ((TEAM == TEAM_BLACK) ? -SCORE : SCORE)

#define TEAM_SCORE_WEIGHT(TEAM) ((TEAM == TEAM_WHITE) ? 1 : -1)

#endif
