
#ifndef CHESS_ENGINE_MACROS_H
#define CHESS_ENGINE_MACROS_H

#define NUMBER_IN_BOUNDS(NUMBER, MINIMUM, MAXIMUM) (NUMBER >= MINIMUM && NUMBER <= MAXIMUM)

#define ABS_SHORT_NUMBER(NUMBER) (((NUMBER) >> 15) ^ (NUMBER)) - ((NUMBER) >> 15)

#define MAX_NUMBER_VALUE(NUMBER1, NUMBER2) (NUMBER2 > NUMBER1) ? NUMBER2 : NUMBER1

#define MIN_NUMBER_VALUE(NUMBER1, NUMBER2) (NUMBER2 < NUMBER1) ? NUMBER2 : NUMBER1

#endif
