
#ifndef ENGINE_FIELD_STATE_H
#define ENGINE_FIELD_STATE_H

#define MASK_STATE_PASSANT(STATE) (STATE & STATE_PASSANT_MASK)
#define MASK_STATE_TURNS(STATE) (STATE & STATE_TURNS_MASK)
#define MASK_STATE_CLOCK(STATE) (STATE & STATE_CLOCK_MASK)
#define MASK_STATE_CURRENT(STATE) (STATE & STATE_CURRENT_MASK)
#define MASK_STATE_CASTLES(STATE) (STATE & STATE_CASTLES_MASK)

#define MASK_WHITE_KSIDE(STATE) (STATE & STATE_WHITE_KSIDE)
#define MASK_WHITE_QSIDE(STATE) (STATE & STATE_WHITE_QSIDE)
#define MASK_BLACK_KSIDE(STATE) (STATE & STATE_BLACK_KSIDE)
#define MASK_BLACK_QSIDE(STATE) (STATE & STATE_BLACK_QSIDE)

#define CLEAR_STATE_PASSANT(STATE) (STATE & ~STATE_PASSANT_MASK)
#define CLEAR_STATE_CLOCK(STATE) (STATE & ~STATE_CLOCK_MASK)
#define CLEAR_STATE_TURNS(STATE) (STATE & ~STATE_TURNS_MASK)
#define CLEAR_STATE_CURRENT(STATE) (STATE & ~STATE_CURRENT_MASK)
#define CLEAR_STATE_CASTLES(STATE) (STATE & ~STATE_CASTLES_MASK)

#define CLEAR_WHITE_KSIDE(STATE) (STATE & ~STATE_WHITE_KSIDE)
#define CLEAR_WHITE_QSIDE(STATE) (STATE & ~STATE_WHITE_QSIDE)
#define CLEAR_BLACK_KSIDE(STATE) (STATE & ~STATE_BLACK_KSIDE)
#define CLEAR_BLACK_QSIDE(STATE) (STATE & ~STATE_BLACK_QSIDE)

#define CLEAR_WHITE_CASTLE(STATE) (STATE & ~STATE_WHITE_KSIDE & ~STATE_WHITE_QSIDE)
#define CLEAR_BLACK_CASTLE(STATE) (STATE & ~STATE_BLACK_KSIDE & ~STATE_BLACK_QSIDE)

#define STATE_CURRENT_MACRO(STATE) (MASK_STATE_CURRENT(STATE) >> STATE_CURRENT_SHIFT)
#define STATE_PASSANT_MACRO(STATE) (MASK_STATE_PASSANT(STATE) >> STATE_PASSANT_SHIFT)
#define STATE_TURNS_MACRO(STATE) (MASK_STATE_TURNS(STATE) >> STATE_TURNS_SHIFT)
#define STATE_CLOCK_MACRO(STATE) (MASK_STATE_CLOCK(STATE) >> STATE_CLOCK_SHIFT)

#define CURRENT_STATE_MACRO(CURRENT) MASK_STATE_CURRENT((CURRENT << STATE_CURRENT_SHIFT))
#define PASSANT_STATE_MACRO(PASSANT) MASK_STATE_PASSANT((PASSANT << STATE_PASSANT_SHIFT))
#define TURNS_STATE_MACRO(TURNS) MASK_STATE_TURNS((TURNS << STATE_TURNS_SHIFT))
#define CLOCK_STATE_MACRO(CLOCK) MASK_STATE_CLOCK((CLOCK << STATE_CLOCK_SHIFT))

#define ALLOC_STATE_CURRENT(STATE, CURRENT) (CLEAR_STATE_CURRENT(STATE) | MASK_STATE_CURRENT(CURRENT))
#define ALLOC_STATE_PASSANT(STATE, PASSANT) (CLEAR_STATE_PASSANT(STATE) | MASK_STATE_PASSANT(PASSANT))
#define ALLOC_STATE_TURNS(STATE, TURNS) (CLEAR_STATE_TURNS(STATE) | MASK_STATE_TURNS(TURNS))
#define ALLOC_STATE_CLOCK(STATE, CLOCK) (CLEAR_STATE_CLOCK(STATE) | MASK_STATE_CLOCK(CLOCK))
#define ALLOC_STATE_CASTLES(STATE, CASTLES) (CLEAR_STATE_CASTLES(STATE) | MASK_STATE_CASTLES(CASTLES))

#define ALLOC_TURNS_STATE(STATE, TURNS) ALLOC_STATE_TURNS(STATE, TURNS_STATE_MACRO(TURNS))
#define ALLOC_CURRENT_STATE(STATE, CURRENT) ALLOC_STATE_CURRENT(STATE, CURRENT_STATE_MACRO(CURRENT))
#define ALLOC_CLOCK_STATE(STATE, CLOCK) ALLOC_STATE_CLOCK(STATE, CLOCK_STATE_MACRO(CLOCK))
#define ALLOC_PASSANT_STATE(STATE, PASSANT) ALLOC_STATE_PASSANT(STATE, PASSANT_STATE_MACRO(PASSANT))

#define STATE_STORE_CURRENT(STATE, CURRENT) (MASK_STATE_CURRENT(STATE) == CURRENT)

#define STATE_TEAM_EXISTS(STATE_TEAM) ((STATE_TEAM == STATE_TEAM_WHITE) || (STATE_TEAM == STATE_TEAM_BLACK))

#define STATE_TEAM_ENEMY(STATE_TEAM) ((STATE_TEAM == STATE_TEAM_WHITE) ? STATE_TEAM_BLACK : ((STATE_TEAM == STATE_TEAM_BLACK) ? STATE_TEAM_WHITE : STATE_TEAM_NONE))

#endif
