
#ifndef ENGINE_FIELD_PIECE_H
#define ENGINE_FIELD_PIECE_H

typedef unsigned short Piece;

#define PIECE_TEAM_MACRO(PIECE) ((PIECE & PIECE_TEAM_MASK) >> PIECE_TEAM_SHIFT)
#define PIECE_TYPE_MACRO(PIECE) ((PIECE & PIECE_TYPE_MASK) >> PIECE_TYPE_SHIFT)

#define TEAM_PIECE_MACRO(TEAM) ((TEAM << PIECE_TEAM_SHIFT) & PIECE_TEAM_MASK)
#define TYPE_PIECE_MACRO(TYPE) ((TYPE << PIECE_TYPE_SHIFT) & PIECE_TYPE_MASK)

#define ALLOC_PIECE_TEAM(PIECE, TEAM) ((PIECE & ~PIECE_TEAM_MASK) | (TEAM & PIECE_TEAM_MASK))
#define ALLOC_PIECE_TYPE(PIECE, TYPE) ((PIECE & ~PIECE_TYPE_MASK) | (TYPE & PIECE_TYPE_MASK))

#define MASK_PIECE_TYPE(PIECE) (PIECE & PIECE_TYPE_MASK)
#define MASK_PIECE_TEAM(PIECE) (PIECE & PIECE_TEAM_MASK)

#define PIECE_STORE_TYPE(PIECE, TYPE) (MASK_PIECE_TYPE(PIECE) == TYPE)

#define PIECE_TYPE_EXISTS(PIECE_TYPE) NUMBER_IN_BOUNDS(PIECE_TYPE_MACRO(PIECE_TYPE), 1, 6)
#define PIECE_TEAM_EXISTS(PIECE_TEAM) ((PIECE_TEAM == PIECE_TEAM_WHITE) || (PIECE_TEAM == PIECE_TEAM_BLACK))

#define CHESS_PIECE_EXISTS(PIECE) (PIECE_TEAM_EXISTS(MASK_PIECE_TEAM(PIECE)) && PIECE_TYPE_EXISTS(MASK_PIECE_TYPE(PIECE)))

#define PIECE_TEAMS_TEAM(PIECE_TEAM1, PIECE_TEAM2) (((PIECE_TEAM1 == PIECE_TEAM_BLACK) && (PIECE_TEAM2 == PIECE_TEAM_BLACK)) || ((PIECE_TEAM1 == PIECE_TEAM_WHITE) && (PIECE_TEAM2 == PIECE_TEAM_WHITE)))
#define PIECE_TEAMS_ENEMY(PIECE_TEAM1, PIECE_TEAM2) (((PIECE_TEAM1 == PIECE_TEAM_BLACK) && (PIECE_TEAM2 == PIECE_TEAM_WHITE)) || ((PIECE_TEAM1 == PIECE_TEAM_WHITE) && (PIECE_TEAM2 == PIECE_TEAM_BLACK)))

#define CHESS_PIECES_TEAM(PIECE1, PIECE2) PIECE_TEAMS_TEAM(MASK_PIECE_TEAM(PIECE1), MASK_PIECE_TEAM(PIECE2))
#define CHESS_PIECES_ENEMY(PIECE1, PIECE2) PIECE_TEAMS_ENEMY(MASK_PIECE_TEAM(PIECE1), MASK_PIECE_TEAM(PIECE2))

#define BOARD_POINT_TEAM(BOARD, POINT) (POINT_INSIDE_BOARD(POINT) ? PIECE_TEAM_MACRO(BOARD[POINT]) : TEAM_NONE)

#define POINT_PIECE_TYPE(BOARD, POINT) (POINT_INSIDE_BOARD(POINT) ? MASK_PIECE_TYPE(BOARD[POINT]) : PIECE_TYPE_NONE)

#define MOVE_START_TEAM(BOARD, MOVE) (MOVE_INSIDE_BOARD(MOVE) ? BOARD_POINT_TEAM(BOARD, MOVE_START_MACRO(MOVE)) : TEAM_NONE)
#define MOVE_START_ENEMY(BOARD, MOVE) (MOVE_INSIDE_BOARD(MOVE) ? NORMAL_TEAM_ENEMY(MOVE_START_TEAM(BOARD, MOVE)) : TEAM_NONE)

#define PIECE_TEAM_ENEMY(PIECE_TEAM) ((PIECE_TEAM == PIECE_TEAM_WHITE) ? PIECE_TEAM_BLACK : ((PIECE_TEAM == PIECE_TEAM_BLACK) ? PIECE_TEAM_WHITE : PIECE_TEAM_NONE))

extern const Piece PIECE_TYPE_NONE;
extern const Piece PIECE_TYPE_PAWN;
extern const Piece PIECE_TYPE_KNIGHT;
extern const Piece PIECE_TYPE_BISHOP;
extern const Piece PIECE_TYPE_ROOK;
extern const Piece PIECE_TYPE_QUEEN;
extern const Piece PIECE_TYPE_KING;

extern const Piece PIECE_TEAM_NONE;
extern const Piece PIECE_TEAM_WHITE;
extern const Piece PIECE_TEAM_BLACK;

extern const Piece PIECE_TEAM_MASK;
extern const Piece PIECE_TYPE_MASK;

extern const unsigned short PIECE_TEAM_SHIFT;
extern const unsigned short PIECE_TYPE_SHIFT;

extern const Piece PIECE_NONE;
extern const Piece PIECE_BLANK;

#endif
