
#ifndef ENGINE_FIELD_INFO_H
#define ENGINE_FIELD_INFO_H

#define MASK_INFO_PASSANT(INFO) (INFO & INFO_PASSANT_MASK)
#define MASK_INFO_TURNS(INFO) (INFO & INFO_TURNS_MASK)
#define MASK_INFO_COUNTER(INFO) (INFO & INFO_COUNTER_MASK)
#define MASK_INFO_TEAM(INFO) (INFO & INFO_TEAM_MASK)
#define MASK_INFO_CASTLES(INFO) (INFO & INFO_CASTLES_MASK)

#define MASK_WHITE_KSIDE(INFO) (INFO & INFO_WHITE_KSIDE)
#define MASK_WHITE_QSIDE(INFO) (INFO & INFO_WHITE_QSIDE)
#define MASK_BLACK_KSIDE(INFO) (INFO & INFO_BLACK_KSIDE)
#define MASK_BLACK_QSIDE(INFO) (INFO & INFO_BLACK_QSIDE)

#define CLEAR_INFO_PASSANT(INFO) (INFO & ~INFO_PASSANT_MASK)
#define CLEAR_INFO_COUNTER(INFO) (INFO & ~INFO_COUNTER_MASK)
#define CLEAR_INFO_TURNS(INFO) (INFO & ~INFO_TURNS_MASK)
#define CLEAR_INFO_TEAM(INFO) (INFO & ~INFO_TEAM_MASK)
#define CLEAR_INFO_CASTLES(INFO) (INFO & ~INFO_CASTLES_MASK)

#define CLEAR_WHITE_KSIDE(INFO) (INFO & ~INFO_WHITE_KSIDE)
#define CLEAR_WHITE_QSIDE(INFO) (INFO & ~INFO_WHITE_QSIDE)
#define CLEAR_BLACK_KSIDE(INFO) (INFO & ~INFO_BLACK_KSIDE)
#define CLEAR_BLACK_QSIDE(INFO) (INFO & ~INFO_BLACK_QSIDE)

#define CLEAR_WHITE_CASTLE(INFO) (INFO & ~INFO_WHITE_KSIDE & ~INFO_WHITE_QSIDE)
#define CLEAR_BLACK_CASTLE(INFO) (INFO & ~INFO_BLACK_KSIDE & ~INFO_BLACK_QSIDE)

#define INFO_TEAM_MACRO(INFO) (MASK_INFO_TEAM(INFO) >> INFO_TEAM_SHIFT)
#define INFO_PASSANT_MACRO(INFO) (MASK_INFO_PASSANT(INFO) >> INFO_PASSANT_SHIFT)
#define INFO_TURNS_MACRO(INFO) (MASK_INFO_TURNS(INFO) >> INFO_TURNS_SHIFT)
#define INFO_COUNTER_MACRO(INFO) (MASK_INFO_COUNTER(INFO) >> INFO_COUNTER_SHIFT)

#define TEAM_INFO_MACRO(TEAM) MASK_INFO_TEAM((TEAM << INFO_TEAM_SHIFT))
#define PASSANT_INFO_MACRO(PASSANT) MASK_INFO_PASSANT((PASSANT << INFO_PASSANT_SHIFT))
#define TURNS_INFO_MACRO(TURNS) MASK_INFO_TURNS((TURNS << INFO_TURNS_SHIFT))
#define COUNTER_INFO_MACRO(COUNTER) MASK_INFO_COUNTER((COUNTER << INFO_COUNTER_SHIFT))

#define ALLOC_INFO_TEAM(INFO, TEAM) (CLEAR_INFO_TEAM(INFO) | MASK_INFO_TEAM(TEAM))
#define ALLOC_INFO_PASSANT(INFO, PASSANT) (CLEAR_INFO_PASSANT(INFO) | MASK_INFO_PASSANT(PASSANT))
#define ALLOC_INFO_TURNS(INFO, TURNS) (CLEAR_INFO_TURNS(INFO) | MASK_INFO_TURNS(TURNS))
#define ALLOC_INFO_COUNTER(INFO, COUNTER) (CLEAR_INFO_COUNTER(INFO) | MASK_INFO_COUNTER(COUNTER))
#define ALLOC_INFO_CASTLES(INFO, CASTLES) (CLEAR_INFO_CASTLES(INFO) | MASK_INFO_CASTLES(CASTLES))

#define ALLOC_TURNS_INFO(INFO, TURNS) ALLOC_INFO_TURNS(INFO, TURNS_INFO_MACRO(TURNS))
#define ALLOC_TEAM_INFO(INFO, TEAM) ALLOC_INFO_TEAM(INFO, TEAM_INFO_MACRO(TEAM))
#define ALLOC_COUNTER_INFO(INFO, COUNTER) ALLOC_INFO_COUNTER(INFO, COUNTER_INFO_MACRO(COUNTER))
#define ALLOC_PASSANT_INFO(INFO, PASSANT) ALLOC_INFO_PASSANT(INFO, PASSANT_INFO_MACRO(PASSANT))

#define INFO_STORE_TEAM(INFO, TEAM) (MASK_INFO_TEAM(INFO) == TEAM)

#define INFO_TEAM_EXISTS(INFO_TEAM) ((INFO_TEAM == INFO_TEAM_WHITE) || (INFO_TEAM == INFO_TEAM_BLACK))

#define INFO_TEAM_ENEMY(INFO_TEAM) ((INFO_TEAM == INFO_TEAM_WHITE) ? INFO_TEAM_BLACK : ((INFO_TEAM == INFO_TEAM_BLACK) ? INFO_TEAM_WHITE : INFO_TEAM_NONE))

#endif
