
#ifndef ENGINE_FIELD_MOVE_H
#define ENGINE_FIELD_MOVE_H

typedef signed short Move;

#define MOVE_STOP_MACRO(MOVE) ((MOVE & MOVE_STOP_MASK) >> MOVE_STOP_SHIFT)
#define MOVE_START_MACRO(MOVE) ((MOVE & MOVE_START_MASK) >> MOVE_START_SHIFT)

#define STOP_MOVE_MACRO(STOP) ((STOP << MOVE_STOP_SHIFT) & MOVE_STOP_MASK)
#define START_MOVE_MACRO(START) ((START << MOVE_START_SHIFT) & MOVE_START_MASK)

#define ALLOC_MOVE_FLAG(MOVE, FLAG) ((MOVE & ~MOVE_FLAG_MASK) | (FLAG & MOVE_FLAG_MASK))
#define ALLOC_MOVE_STOP(MOVE, STOP) ((MOVE & ~MOVE_STOP_MASK) | (STOP & MOVE_STOP_MASK))
#define ALLOC_MOVE_START(MOVE, START) ((MOVE & ~MOVE_START_MASK) | (START & MOVE_START_MASK))

#define MOVE_STOP_FILE(MOVE) POINT_FILE_MACRO(MOVE_STOP_MACRO(MOVE))
#define MOVE_STOP_RANK(MOVE) POINT_RANK_MACRO(MOVE_STOP_MACRO(MOVE))
#define MOVE_START_FILE(MOVE) POINT_FILE_MACRO(MOVE_START_MACRO(MOVE))
#define MOVE_START_RANK(MOVE) POINT_RANK_MACRO(MOVE_START_MACRO(MOVE))

#define MOVE_STORE_FLAG(MOVE, FLAG) (MASK_MOVE_FLAG(MOVE) == FLAG)
#define MASK_MOVE_FLAG(MOVE) (MOVE & MOVE_FLAG_MASK)

#define MOVE_PROMOTE_FLAG(MOVE) MOVE_FLAG_PROMOTE(MASK_MOVE_FLAG(MOVE))
#define MOVE_FLAG_PROMOTE(FLAG) ((FLAG == MOVE_FLAG_KNIGHT) || (FLAG == MOVE_FLAG_BISHOP) || (FLAG == MOVE_FLAG_ROOK) || (FLAG == MOVE_FLAG_QUEEN))

#define START_STOP_MOVE(START, STOP) (START_MOVE_MACRO(START) | STOP_MOVE_MACRO(STOP))

#define MOVE_START_PIECE(BOARD, MOVE) (MOVE_INSIDE_BOARD(MOVE) ? BOARD[MOVE_START_MACRO(MOVE)] : PIECE_NONE)
#define MOVE_STOP_PIECE(BOARD, MOVE) (MOVE_INSIDE_BOARD(MOVE) ? BOARD[MOVE_STOP_MACRO(MOVE)] : PIECE_NONE)

#define MOVE_INSIDE_BOARD(MOVE) ((MOVE != MOVE_NONE) && (MOVE >= 0))

#define INVERT_CHESS_MOVE(MOVE) START_STOP_MOVE(MOVE_STOP_MACRO(MOVE), MOVE_START_MACRO(MOVE))

#define MOVE_OFFSET_FACTOR(MOVE_OFFSET) ((MOVE_OFFSET == 0) ? 0 : ((MOVE_OFFSET > 0) ? 1 : -1))

#define MOVE_POINTS_TEAM(BOARD, MOVE) BOARD_POINTS_TEAM(BOARD, MOVE_START_MACRO(MOVE), MOVE_STOP_MACRO(MOVE))
#define MOVE_POINTS_ENEMY(BOARD, MOVE) BOARD_POINTS_ENEMY(BOARD, MOVE_START_MACRO(MOVE), MOVE_STOP_MACRO(MOVE))

#define START_PIECE_TYPE(BOARD, MOVE) (MOVE_INSIDE_BOARD(MOVE) ? POINT_PIECE_TYPE(BOARD, MOVE_START_MACRO(MOVE)) : PIECE_TYPE_NONE)
#define STOP_PIECE_TYPE(BOARD, MOVE) (MOVE_INSIDE_BOARD(MOVE) ? POINT_PIECE_TYPE(BOARD, MOVE_STOP_MACRO(MOVE)) : PIECE_TYPE_NONE)

#define BOARD_MOVE_PATTERN(MOVE) (MOVE_STOP_MACRO(MOVE) - MOVE_START_MACRO(MOVE))

extern const Move MOVE_FLAG_NONE;
extern const Move MOVE_FLAG_KNIGHT;
extern const Move MOVE_FLAG_BISHOP;
extern const Move MOVE_FLAG_ROOK;
extern const Move MOVE_FLAG_QUEEN;
extern const Move MOVE_FLAG_DOUBLE;
extern const Move MOVE_FLAG_CASTLE;
extern const Move MOVE_FLAG_PASSANT;

extern const Move MOVE_STOP_MASK;
extern const Move MOVE_START_MASK;
extern const Move MOVE_FLAG_MASK;

extern const unsigned short MOVE_STOP_SHIFT;
extern const unsigned short MOVE_START_SHIFT;

extern const Move MOVE_NONE;
extern const Move MOVE_BLANK;

#endif
