
#ifndef ENGINE_FIELD_STATE_H
#define ENGINE_FIELD_STATE_H

#define MASK_STATE_PASSANT(STATE) (STATE & STATE_PASSANT_MASK)
#define MASK_STATE_TURNS(STATE) (STATE & STATE_TURNS_MASK)
#define MASK_STATE_COUNTER(STATE) (STATE & STATE_COUNTER_MASK)
#define MASK_STATE_TEAM(STATE) (STATE & STATE_TEAM_MASK)
#define MASK_STATE_CASTLES(STATE) (STATE & STATE_CASTLES_MASK)

#define MASK_WHITE_KSIDE(STATE) (STATE & STATE_WHITE_KSIDE)
#define MASK_WHITE_QSIDE(STATE) (STATE & STATE_WHITE_QSIDE)
#define MASK_BLACK_KSIDE(STATE) (STATE & STATE_BLACK_KSIDE)
#define MASK_BLACK_QSIDE(STATE) (STATE & STATE_BLACK_QSIDE)

#define CLEAR_STATE_PASSANT(STATE) (STATE & ~STATE_PASSANT_MASK)
#define CLEAR_STATE_COUNTER(STATE) (STATE & ~STATE_COUNTER_MASK)
#define CLEAR_STATE_TURNS(STATE) (STATE & ~STATE_TURNS_MASK)
#define CLEAR_STATE_TEAM(STATE) (STATE & ~STATE_TEAM_MASK)
#define CLEAR_STATE_CASTLES(STATE) (STATE & ~STATE_CASTLES_MASK)

#define CLEAR_WHITE_KSIDE(STATE) (STATE & ~STATE_WHITE_KSIDE)
#define CLEAR_WHITE_QSIDE(STATE) (STATE & ~STATE_WHITE_QSIDE)
#define CLEAR_BLACK_KSIDE(STATE) (STATE & ~STATE_BLACK_KSIDE)
#define CLEAR_BLACK_QSIDE(STATE) (STATE & ~STATE_BLACK_QSIDE)

#define CLEAR_WHITE_CASTLE(STATE) (STATE & ~STATE_WHITE_KSIDE & ~STATE_WHITE_QSIDE)
#define CLEAR_BLACK_CASTLE(STATE) (STATE & ~STATE_BLACK_KSIDE & ~STATE_BLACK_QSIDE)

#define STATE_TEAM_MACRO(STATE) (MASK_STATE_TEAM(STATE) >> STATE_TEAM_SHIFT)
#define STATE_PASSANT_MACRO(STATE) (MASK_STATE_PASSANT(STATE) >> STATE_PASSANT_SHIFT)
#define STATE_TURNS_MACRO(STATE) (MASK_STATE_TURNS(STATE) >> STATE_TURNS_SHIFT)
#define STATE_COUNTER_MACRO(STATE) (MASK_STATE_COUNTER(STATE) >> STATE_COUNTER_SHIFT)

#define TEAM_STATE_MACRO(TEAM) MASK_STATE_TEAM((TEAM << STATE_TEAM_SHIFT))
#define PASSANT_STATE_MACRO(PASSANT) MASK_STATE_PASSANT((PASSANT << STATE_PASSANT_SHIFT))
#define TURNS_STATE_MACRO(TURNS) MASK_STATE_TURNS((TURNS << STATE_TURNS_SHIFT))
#define COUNTER_STATE_MACRO(COUNTER) MASK_STATE_COUNTER((COUNTER << STATE_COUNTER_SHIFT))

#define ALLOC_STATE_TEAM(STATE, TEAM) (CLEAR_STATE_TEAM(STATE) | MASK_STATE_TEAM(TEAM))
#define ALLOC_STATE_PASSANT(STATE, PASSANT) (CLEAR_STATE_PASSANT(STATE) | MASK_STATE_PASSANT(PASSANT))
#define ALLOC_STATE_TURNS(STATE, TURNS) (CLEAR_STATE_TURNS(STATE) | MASK_STATE_TURNS(TURNS))
#define ALLOC_STATE_COUNTER(STATE, COUNTER) (CLEAR_STATE_COUNTER(STATE) | MASK_STATE_COUNTER(COUNTER))
#define ALLOC_STATE_CASTLES(STATE, CASTLES) (CLEAR_STATE_CASTLES(STATE) | MASK_STATE_CASTLES(CASTLES))

#define ALLOC_TURNS_STATE(STATE, TURNS) ALLOC_STATE_TURNS(STATE, TURNS_STATE_MACRO(TURNS))
#define ALLOC_TEAM_STATE(STATE, TEAM) ALLOC_STATE_TEAM(STATE, TEAM_STATE_MACRO(TEAM))
#define ALLOC_COUNTER_STATE(STATE, COUNTER) ALLOC_STATE_COUNTER(STATE, COUNTER_STATE_MACRO(COUNTER))
#define ALLOC_PASSANT_STATE(STATE, PASSANT) ALLOC_STATE_PASSANT(STATE, PASSANT_STATE_MACRO(PASSANT))

#define STATE_STORE_TEAM(STATE, TEAM) (MASK_STATE_TEAM(STATE) == TEAM)

#define STATE_TEAM_EXISTS(STATE_TEAM) ((STATE_TEAM == STATE_TEAM_WHITE) || (STATE_TEAM == STATE_TEAM_BLACK))

#define STATE_TEAM_ENEMY(STATE_TEAM) ((STATE_TEAM == STATE_TEAM_WHITE) ? STATE_TEAM_BLACK : ((STATE_TEAM == STATE_TEAM_BLACK) ? STATE_TEAM_WHITE : STATE_TEAM_NONE))

#endif
