
#ifndef FIELD_PARTS_HANDLER_H
#define FIELD_PARTS_HANDLER_H

#define NORMAL_TEAM_EXISTS(TEAM) ((TEAM == TEAM_WHITE) || (TEAM == TEAM_BLACK))

#define NORMAL_TEAM_ENEMY(TEAM) ((TEAM == TEAM_WHITE) ? TEAM_BLACK : ((TEAM == TEAM_BLACK) ? TEAM_WHITE : TEAM_NONE))

#define NORMAL_TEAMS_TEAM(TEAM1, TEAM2) (((TEAM1 == TEAM_WHITE) && (TEAM2 == TEAM_WHITE)) || ((TEAM1 == TEAM_BLACK) && (TEAM2 == TEAM_BLACK)))

#define NORMAL_TEAMS_ENEMY(TEAM1, TEAM2) (((TEAM1 == TEAM_BLACK) && (TEAM2 == TEAM_WHITE)) || ((TEAM1 == TEAM_WHITE) && (TEAM2 == TEAM_BLACK)))

#endif
