
#include "../Header-Files-Folder/screen-include-file.h"

const Uint32 BUTTON_UP = SDL_MOUSEBUTTONUP;
const Uint32 BUTTON_DOWN = SDL_MOUSEBUTTONDOWN;
const Uint8 LEFT_BUTTON = SDL_BUTTON_LEFT;
const Uint8 RIGHT_BUTTON = SDL_BUTTON_RIGHT;

const int WINDOW_CENTER = SDL_WINDOWPOS_CENTERED;
const Uint32 WINDOW_RESIZE = SDL_WINDOW_RESIZABLE;
const Uint32 WINDOW_OPENGL = SDL_WINDOW_OPENGL;
const Uint32 WINDOW_SHOWN = SDL_WINDOW_SHOWN;
